### PR TITLE
Update to normal and fix errors

### LINKED ISSUE #2: Leave the queue
You are not leaving the queue when you click the option!

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
- Fix leave queue (#2)
- Update config system to the actual config module system
- Improve code style
- Delete header file

Close #2

### CODE REVIEW

**Comment by milestorme** [comment]
@Winfidonarleyan can you please solve conflicts for merge 😊

**Comment by milestorme** [comment]
I have reports that the build is broken after this merge

**Comment by BarbzYHOOL** [comment]
Winfi, did you test it ingame? @Winfidonarleyan

**Comment by poszer** [comment]
Before merging, how i know AC practice first to test it, than merge. But in this case, that practice is lost. Make a clone of this module, and check issues Winfi

**Comment by Winfidonarleyan** [comment]
Yes

**Pull request merged**
