### PR TITLE
feat: Changed to support 1v1 queue and added non hard coded forbiden talents

### PR DESCRIPTION
**Pull request by peti446**
Requires this PR to be merged: https://github.com/azerothcore/azerothcore-wotlk/pull/3508 before this can be merged without errors.

Fixes: https://github.com/azerothcore/mod-1v1-arena/issues/15 https://github.com/azerothcore/mod-1v1-arena/issues/13 https://github.com/azerothcore/mod-1v1-arena/issues/12

Features and changes:
The arena will now work over its own queue instead of 5v5
Added a new config file with the option to set the blocked talents list
The arena crystals work correctly

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
@peti46 thanks, please notify me or a staff here and in the discord when it needs to be merged if it's not done (i don't check my github notif lol)

very nice fixes if all goes well

are u in that discord?

**Comment by peti446** [comment]
@BarbzYHOOL Yep will do once it's mergeable, I am indeed on the discord.

**Comment by nicoaravena** [comment]
@peti446 Just trying to test this pr, but found some errors with the following functions:

- Some functions are marked as override and there are not defined in the core.
- GetArenaTeamByCaptain: receive one param, in the file is not override in any place and when it is used, will pass two params (ARENA_TEAM_1V1 as extra)
- class team_1v1arena : public ArenaTeamScript has an error, maybe the class ArenaTeamScript exists on other core, but not in AC
- Other minor warnings found.

**Comment by peti446** [comment]
@nicoaravena All the functions required are in this pr azerothcore/azerothcore-wotlk#3508  waiting to be accepted and merged for this to actually work. You will need these changes to test this pr othewise it will not compile at all.

**Comment by nicoaravena** [comment]
@peti446 I will be testing that PR asap, hope today or tomorrow. Thanks for the details.

**Comment by nicoaravena** [comment]
Two warnings in compile atm, on file npc_arena1v1.cpp
Line 86: condition compares two different types in `minslot < sConfigMgr->GetIntDefault("Arena1v1.ArenaSlotID", 3)` (uint32 and int)
Line 268: Variable `bgTypeId` is no used.
---
Also, when trying to join unrated or rated queue, I have this error on console `Battleground: template bg (all arenas) not found`

**Review by Helias — APPROVED** [review]

**Comment by peti446** [comment]
@nicoaravena Thanks will have a look at the warnings late and update it. Thanks!

**Comment by peti446** [comment]
@Helias @BarbzYHOOL This can now be merged , not sure how to re run the checks.

**Comment by FrancescoBorzi** [comment]
> @Helias @BarbzYHOOL This can now be merged , not sure how to re run the checks.

I've restarted the checks

**Comment by peti446** [comment]
@FrancescoBorzi Thanks :D Sorry for the close/reopen thought that would do it.

**Comment by FrancescoBorzi** [comment]
@peti446 no problem, all checks passed!

**Pull request merged**
