### PR TITLE
WIP - feat: Add forbidden talent list

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
I don't know why it was commented out

EDIT: ok so if someone could add the forbidden talent list code, it's probably available in the original c++ TC script

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
This unused

**Comment by BarbzYHOOL** [comment]
ok, the code related to FORBIDDEN_TALENTS is missing

**Comment by Winfidonarleyan** [comment]
yes yes

**Comment by BarbzYHOOL** [comment]
i added it back, will make a PR later

**Pull request closed without merging**
