### PR TITLE
Update npc_arena1v1.cpp

### PR DESCRIPTION
**Pull request by Bogir**

### CODE REVIEW

**Comment by Tony931023** [comment]
i will try the pr right away

**Comment by Tony931023** [comment]
perfect @Bogir  works without problem

**Comment by Bogir** [comment]
@Winfidonarleyan take a look plz

**Review by Helias — APPROVED** [review]

**Comment by porkserver** [comment]
Mod builds but players cannot enter arena on queue pop.  works as intended till then.

**Comment by porkserver** [comment]
Did some further testing on a fresh clean install and new database.  Mod works up until the arena queue pops.
It shows that an arena has been created and a timer begins but player is not teleported in.  minimap icon acts normally, same issue there... when you manually select enter arena, nothing happens. 
Screen Shot 2022-03-25 at 8 33 40 AM
Screen Shot 2022-03-25 at 8 33 28 AM
Screen Shot 2022-03-25 at 8 33 13 AM

**Comment by Nelnamara** [comment]
I've been trying different settings and something else is not working since the big BG update.  The mod does not seem to be setting the arenatype to 1.

Console kicks error that no Arena type 0 exists
Screen Shot 2022-04-10 at 12 41 12 PM
.

**Comment by pangolp** [comment]
Greetings. What is the current status of this pull request? Some people mentioned that with these changes, the problem would be solved, but now it has to be updated, because apparently, there were changes and generate a conflict. However, I don't know if in the end, it serves to improve the mentioned problems. I would like to know, to update it, or to close it, if you are not going to work on it anymore.

**Comment by pangolp** [comment]
I have been working on a pull request, I think it can solve some of the issues that are discussed here, and that are also within the issues. But I need to test it, so if anyone wants to test it, excellent. The only thing that needs to be corrected is that when you create the team, many times it assigns you honor points / arenas, which should not be assigned to you. But other than that, the rest, I think it would be fine.

**Pull request closed without merging**
