### PR TITLE
feat. Upgrade module to latest kernel version

### PR DESCRIPTION
**Pull request by pangolp**
- The issues template is added
- Pull request template added
- Include.sh content is removed
- New sql folder format is added.
- Updated workflows

### CODE REVIEW

**Comment by Helias** [comment]
good job man!

**Comment by pangolp** [comment]
> good job man!

We have to try to put the template, to most of the modules, because if not, many times we do not have the necessary information, to be able to know what the problem is, and try to solve it.

**Comment by Helias** [comment]
About the template issue or PR I was wondering if it is possible to create a "reusable template" like the reusable workflows for the github action, like a centralize issue_template.md file in one single repository used from many other repositories, instead of copy/paste the same template into all modules

**Comment by pangolp** [comment]
> About the template issue or PR I was wondering if it is possible to create a "reusable template" like the reusable workflows for the github action, like a centralize issue_template.md file in one single repository used from many other repositories, instead of copy/paste the same template into all modules

De hecho, el actual [mod-skeleton](https://github.com/azerothcore/skeleton-module), tiene ya los issue incorporados y los pull_request. Pasa que para estos módulos viejos, tenes que hacerlo de manera manual. Pero los nuevos módulos, ya vienen con los template y otras configuraciones mas.

**Pull request merged**
