### PR TITLE
Fix arena 1v1 (queue and arena end)

### PR DESCRIPTION
**Pull request by Rastrian**
- Related PR needed to make it work: https://github.com/azerothcore/azerothcore-wotlk/pull/11820
- Tested with the lastest AC 

image
image

### CODE REVIEW

**Comment by auguzsto** [comment]
Its work's!!!!!! Thankssssssssssssssssssss

**Comment by Helias** [comment]
Thank you for your PR!

**Comment by Rastrian** [comment]
> Thank you for your PR!

Please close this issue:
https://github.com/azerothcore/mod-1v1-arena/issues/38

**Comment by Helias** [comment]
Done, thank you 👍

**Pull request merged**
